### ISSUE TITLE
path_planning memory corruption?!

### ISSUE THREAD

**Issue by raoping2017** [jeremy-shannon/CarND-Path-Planning-Project#1]
run path_planning first,and open term3_sim.x86_64, and then show the following error: 
dev@ubuntu:~/udacity_car/CarND-Path-Planning-Project/build$ ./path_planning Listening to port 4567
*** Error in `./path_planning': malloc(): memory corruption: 0x0000000000d64b90 ***
Aborted (core dumped)

gdb it, the following is the error detail:
GNU gdb (Ubuntu 7.7-0ubuntu3.1) 7.7
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from path_planning...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/raoping/udacity_car/CarND-Path-Planning-Project/build/path_planning 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Listening to port 4567
*** Error in `/home/raoping/udacity_car/CarND-Path-Planning-Project/build/path_planning': malloc(): memory corruption: 0x000000000069ab90 ***

Program received signal SIGABRT, Aborted.
0x00007ffff68f4f79 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff68f4f79 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff68f8388 in __GI_abort () at abort.c:89
#2  0x00007ffff69321d4 in __libc_message (do_abort=1, fmt=fmt@entry=0x7ffff6a40a10 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff693fd76 in malloc_printerr (ptr=0x69ab90, str=0x7ffff6a3cb84 "malloc(): memory corruption", action=<optimized out>)
    at malloc.c:4996
#4  _int_malloc (av=0x7ffff6c7d760 <main_arena>, bytes=144) at malloc.c:3447
#5  0x00007ffff69415f0 in __GI___libc_malloc (bytes=144) at malloc.c:2891
#6  0x00007ffff722cf88 in operator new (sz=144) at ../../../../gcc-5.4.0/libstdc++-v3/libsupc++/new_op.cc:50
#7  0x00007ffff7533306 in uWS::Hub::onServerAccept(uS::Socket) () from /usr/lib/libuWS.so
#8  0x00007ffff7535ba1 in void uS::Node::accept_poll_cb<&uWS::Hub::onServerAccept>(uv_poll_s*, int, int) () from /usr/lib/libuWS.so
#9  0x00007ffff775834c in uv.io_poll () from /usr/lib/x86_64-linux-gnu/libuv.so.0.10
#10 0x00007ffff774a6fc in uv_run () from /usr/lib/x86_64-linux-gnu/libuv.so.0.10
#11 0x000000000040e0aa in main ()

**Comment by jeremy-shannon** [comment]
I can't offer support for this code. It's over a year old now and probably incompatible with the current Udacity simulator at this point.
